apiVersion: batch/v1
kind: Job
metadata:
  name:  minnie65-download-meshes
spec:
  parallelism: 24 # number of jobs to deploy ; Allen requests a limit of 5
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      volumes: # Example volume mounting
      - name: mnt # name for the volume to be reference in container volumeMounts
        hostPath:
          path: /mnt # Directory on the host machine to be mounted
      affinity: # Affinity to select certain nodes with 11GB, 12GB, or 24GB memory
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # Require nodes to have this label
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname # Target label is gpu_mem_size
                operator: In # Key must have one of the following values
                values:
                - at-compute003
                - at-compute004
                - at-compute005
                - at-compute006
      containers:
      - name: minnie65-download-meshes
        image: at-docker.ad.bcm.edu:5000/microns-materialization
        resources:
          requests:
            cpu: 1
            memory: 5Gi
        volumeMounts: # Container reference to volumes define above
        - name: mnt # Name of the volume define above
          mountPath: /mnt # Location of where to mount it in the container
        env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
        command: ["/bin/sh"]
        args: ["-c", "python3 -u /src/microns-materialization/deploy/kubernetes/minnie65_download_meshes.py"] # path to script